#!/usr/bin/env node
/**
 * Writes generated environment helper files from .env / process.env:
 * - src/environments/api-key.ts (OpenWeather)
 * - src/environments/firebase-config.ts (Firebase web config)
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const envDir = path.join(root, 'src', 'environments');

function readDotEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  return Object.fromEntries(
    fs
      .readFileSync(filePath, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const index = line.indexOf('=');
        const key = line.slice(0, index).trim();
        const value = line.slice(index + 1).trim().replace(/^['"]|['"]$/g, '');
        return [key, value];
      }),
  );
}

function pick(fromFile, name) {
  return process.env[name] || fromFile[name] || '';
}

const fromFile = readDotEnv(envPath);

const openWeatherApiKey = pick(fromFile, 'OPENWEATHER_API_KEY');
fs.writeFileSync(
  path.join(envDir, 'api-key.ts'),
  `/** Generated by scripts/inject-env.js — do not commit secrets. */\n` +
    `export const openWeatherApiKey = ${JSON.stringify(openWeatherApiKey)};\n`,
);

const firebaseConfig = {
  apiKey: pick(fromFile, 'FIREBASE_API_KEY'),
  authDomain: pick(fromFile, 'FIREBASE_AUTH_DOMAIN'),
  projectId: pick(fromFile, 'FIREBASE_PROJECT_ID'),
  storageBucket: pick(fromFile, 'FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: pick(fromFile, 'FIREBASE_MESSAGING_SENDER_ID'),
  appId: pick(fromFile, 'FIREBASE_APP_ID'),
  measurementId: pick(fromFile, 'FIREBASE_MEASUREMENT_ID'),
};

const e2eAuthBypass = pick(fromFile, 'E2E_AUTH_BYPASS') === 'true';

fs.writeFileSync(
  path.join(envDir, 'firebase-config.ts'),
  `/** Generated by scripts/inject-env.js — do not commit secrets. */\n` +
    `export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)} as const;\n` +
    `export const e2eAuthBypass = ${JSON.stringify(e2eAuthBypass)};\n`,
);

if (!openWeatherApiKey) {
  console.warn('[inject-env] OPENWEATHER_API_KEY is empty.');
} else {
  console.log('[inject-env] Wrote api-key.ts');
}

if (!firebaseConfig.apiKey || !firebaseConfig.projectId) {
  console.warn('[inject-env] Firebase config is incomplete. Set FIREBASE_* in .env or CI/Vercel secrets.');
} else {
  console.log('[inject-env] Wrote firebase-config.ts');
}
