#!/usr/bin/env node
/**
 * Writes generated environment helper files from .env / process.env:
 * - src/environments/api-key.ts (OpenWeather)
 * - src/environments/firebase-config.ts (Firebase web config)
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const envDir = path.join(root, 'src', 'environments');

/** Placeholder so initializeApp never receives empty strings (CI e2e / local without secrets). */
const FIREBASE_PLACEHOLDER = {
  apiKey: 'demo-api-key',
  authDomain: 'demo-project.firebaseapp.com',
  projectId: 'demo-project',
  storageBucket: 'demo-project.appspot.com',
  messagingSenderId: '000000000000',
  appId: '1:000000000000:web:0000000000000000000000',
  measurementId: 'G-DEMO000000',
};

function readDotEnv(filePath) {
  if (!fs.existsSync(filePath)) {
    return {};
  }

  return Object.fromEntries(
    fs
      .readFileSync(filePath, 'utf8')
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const index = line.indexOf('=');
        const key = line.slice(0, index).trim();
        const value = line.slice(index + 1).trim().replace(/^['"]|['"]$/g, '');
        return [key, value];
      }),
  );
}

function pick(fromFile, name) {
  return process.env[name] || fromFile[name] || '';
}

const fromFile = readDotEnv(envPath);

const openWeatherApiKey = pick(fromFile, 'OPENWEATHER_API_KEY');
fs.writeFileSync(
  path.join(envDir, 'api-key.ts'),
  `/** Generated by scripts/inject-env.js — do not commit secrets. */\n` +
    `export const openWeatherApiKey = ${JSON.stringify(openWeatherApiKey)};\n`,
);

const pickedFirebase = {
  apiKey: pick(fromFile, 'FIREBASE_API_KEY'),
  authDomain: pick(fromFile, 'FIREBASE_AUTH_DOMAIN'),
  projectId: pick(fromFile, 'FIREBASE_PROJECT_ID'),
  storageBucket: pick(fromFile, 'FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: pick(fromFile, 'FIREBASE_MESSAGING_SENDER_ID'),
  appId: pick(fromFile, 'FIREBASE_APP_ID'),
  measurementId: pick(fromFile, 'FIREBASE_MEASUREMENT_ID'),
};

const firebaseComplete = Boolean(pickedFirebase.apiKey && pickedFirebase.projectId && pickedFirebase.appId);
const firebaseConfig = firebaseComplete
  ? pickedFirebase
  : {
      ...FIREBASE_PLACEHOLDER,
      ...Object.fromEntries(Object.entries(pickedFirebase).filter(([, value]) => Boolean(value))),
    };

const e2eAuthBypass = pick(fromFile, 'E2E_AUTH_BYPASS') === 'true';

fs.writeFileSync(
  path.join(envDir, 'firebase-config.ts'),
  `/** Generated by scripts/inject-env.js — do not commit secrets. */\n` +
    `export const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)} as const;\n` +
    `export const e2eAuthBypass = ${JSON.stringify(e2eAuthBypass)};\n`,
);

if (!openWeatherApiKey) {
  console.warn('[inject-env] OPENWEATHER_API_KEY is empty.');
} else {
  console.log('[inject-env] Wrote api-key.ts');
}

if (!firebaseComplete) {
  console.warn(
    '[inject-env] Firebase secrets incomplete — wrote placeholder config so the app can boot (e2e / local).',
  );
} else {
  console.log('[inject-env] Wrote firebase-config.ts');
}

console.log(`[inject-env] e2eAuthBypass=${e2eAuthBypass}`);
